all:
	gcc chesspernado.c ch_board.c ch_cmd.c init_setup.c waves.c ai_movement.c list.c special_moves.c menu.c tutorial.c game_simulation.c -o chesspernado
other:
	gcc chess/ch_board.c chess/ch_cmd.c chess/ch_danger.c chess/chess.c chess/list.c chess/redo_undo.c chess/checkmate.c chess/stalemate.c -o chess/a.out
